import { createContext, useCallback, useContext, useMemo, useState, type ReactNode } from "react";

export type Lang = "en" | "pt";

const translations = {
  en: {
    welcome: "Welcome to Samphone's online store",
    phone: "+351-937119295",
    registration: "Registration",
    login: "Log In",
    searchPlaceholder: "To Search For...",
    compare: "Compare",
    wishlist: "Wishlist",
    allCategories: "All Categories",
    nav_home: "HOME",
    nav_accessories: "ACCESSORIES",
    nav_smartphones: "SMARTPHONES",
    nav_cards: "CARDS",
    nav_new: "NEW",
    nav_multibrand: "MULTI BRAND",
    nav_contact: "CONTACT US",
    hero_badge: "Lisbon's #1 Tech Boutique",
    hero_line1: "Your Phone.",
    hero_line2: "Your Parts.",
    hero_line3: "Delivered Fast.",
    hero_sub: "Premium accessories and pro-grade repair parts for over 700+ device models. Fast delivery across Lisbon and Portugal.",
    hero_shop: "Shop Now",
    hero_browse: "Browse Categories",
    hero_scroll: "Scroll to explore brands",
    hero_rating: "4.9/5 Rating",
    hero_rating_sub: "from 600+ happy customers",
    addToCart: "Add to Cart",
    viewParts: "View Parts",
    products_title: "Top Picks This Week",
    products_sub: "Thousands of products. Competitive prices. Shipped fast from Lisbon.",
    viewAll: "View All Products",
    popularProducts: "Popular Products",
    productNotFound: "We could not find this product.",
    backToHome: "Back to home",
    backToShopping: "Back to shopping",
    reviewsLabel: "reviews",
    newArrivals_section_title: "New Arrivals",
    newArrivals_section_sub: "Just landed — check out our latest additions!",
    newArrivals_see_all: "See All",
    newArrivals_page: "Page",
    newArrivals_of: "of",
    loginToSeePrice: "Log in to see price",
    loginForPricing: "Sign in to view prices and add items to your cart.",
    auth_register_title: "Create account",
    auth_login_title: "Welcome back",
    auth_email: "Email",
    auth_password: "Password",
    auth_name: "Full name",
    auth_submit_login: "Sign in",
    auth_submit_register: "Create account",
    auth_no_account: "No account yet?",
    auth_has_account: "Already have an account?",
    auth_logout: "Log out",
    auth_my_account: "My account",
    account_title: "My Account",
    account_dashboard: "Dashboard",
    account_welcome: "You're signed in. Browse the store to see prices and shop.",
    account_profile_hint: "Complete your profile to speed up checkout.",
    breadcrumb_home: "Home",
    product_gallery_tab: "Gallery & zoom",
    product360_tab: "360° view",
    product360_title: "360° product view",
    product360_hint: "Drag left or right to rotate (demo uses your product image in 3D).",
    compare_page_title: "Compare devices",
    compare_page_sub: "Side-by-side specifications for parts and devices.",
    compare_empty: "Add up to 3 products from their pages, then open compare again.",
    compare_add: "Add to compare",
    compare_remove: "Remove",
    compare_view: "Open compare",
    compare_max_note: "Maximum 3 products. Oldest is replaced when adding a fourth.",
    nav_cart: "Cart",
    cart_page_title: "Your cart",
    cart_page_sub: "Review items and quantities. Prices shown when signed in.",
    cart_clear: "Clear cart",
    cart_empty_title: "Your cart is empty",
    cart_empty_body: "Browse the store and use the cart icon on product cards to add items.",
    cart_remove_line: "Remove",
    cart_subtotal: "Subtotal",
    cart_subtotal_partial: "Some items have no listed price; subtotal may be incomplete.",
    cart_checkout_note: "Checkout is demo-only — totals use visible catalog prices.",
    cart_checkout_cta: "Proceed to checkout",
    cart_items_count: "{count} items in cart",
    wishlist_page_title: "Wishlist",
    wishlist_page_sub: "Products you saved for later.",
    wishlist_empty_title: "Your wishlist is empty",
    wishlist_empty_body: "Use the heart on product cards to save items here.",
    wishlist_remove: "Saved — tap to remove",
    wishlist_save: "Save to wishlist",
    product_description_title: "Product description",
    product_details_title: "Product details",
    product_compatibility: "Compatibility",
    product_in_stock: "In stock",
    related_accessories_title: "Related accessories",
    related_accessories_see_all: "See all",
    woo_sku: "SKU",
    woo_categories_label: "Categories",
    woo_product_type: "Product type",
    recently_viewed_title: "Recently viewed",
    compare_table_feature: "Feature",
    compare_clear_all: "Clear all",
    stock_low: "Only {count} left in stock",
    stock_in: "{count} in stock",
    delivery_title: "Delivery estimate",
    delivery_region: "Ship to",
    delivery_zone_lisbon: "Lisbon metro",
    delivery_zone_portugal: "Portugal mainland",
    delivery_zone_islands: "Islands",
    delivery_speed_standard: "Standard",
    delivery_speed_express: "Express",
    delivery_speed_label: "Speed",
    delivery_arrives: "Estimated arrival",
    nav_track: "Track order",
    nav_book_repair: "Book repair",
    nav_trade_in: "Trade-in",
    nav_diagnostics: "Diagnostics",
    track_title: "Track your order",
    track_sub: "Enter your order ID from the confirmation email or your account.",
    track_placeholder: "e.g. SP-LIS-…",
    track_button: "Track",
    track_not_found: "We couldn’t find that order. Check the ID or contact us on WhatsApp.",
    track_order_label: "Order",
    track_step_ordered: "Order placed",
    track_step_packed: "Packed",
    track_step_shipped: "Shipped",
    track_step_delivery: "Out for delivery",
    track_step_done: "Delivered",
    track_items: "Items",
    support_open: "Help & chat",
    support_tab_live: "Live",
    support_tab_faq: "FAQ assistant",
    support_tab_callback: "Callback",
    support_live_blurb: "Fastest: WhatsApp or visit us in Lisbon. We reply Mon–Sat during store hours.",
    support_chat_whatsapp: "Open WhatsApp",
    support_faq_placeholder: "Ask about shipping, repairs, returns…",
    support_faq_send: "Ask",
    support_callback_hint: "We’ll call you back shortly during business hours.",
    support_callback_phone: "Phone number",
    support_callback_ok: "Request sent — we’ll call you soon.",
    support_callback_submit: "Request call",
    people_also_bought_title: "People also bought",
    recommended_title: "Recommended for you",
    recommended_sub: "Based on what you browse",
    search_no_results: "No matching products",
    search_suggestions: "Suggestions",
    account_orders: "Your orders",
    account_track_link: "Track shipment",
    account_create_order: "Create order from cart",
    account_order_created: "Order created. Save this ID:",
    account_no_orders: "No orders yet. Add items to your cart and create an order here.",
    book_repair_title: "Book a repair",
    book_repair_sub: "Pick services and urgency — totals update live.",
    book_device_hint: "Device (brand / model)",
    book_notes: "Notes",
    book_services_label: "Services",
    book_urgency_standard: "Standard (3–5 days)",
    book_urgency_same_day: "Same-day (+€25)",
    book_total: "Estimated total",
    book_submit: "Submit booking request",
    book_ok: "Booking received — we’ll confirm by WhatsApp or phone.",
    trade_title: "Trade-in estimator",
    trade_sub: "Get a voucher toward your next purchase.",
    trade_brand: "Brand",
    trade_age: "Device age (years)",
    trade_condition: "Condition",
    trade_estimate: "Estimated value",
    trade_code_label: "Your voucher code",
    trade_copy: "Copy code",
    trade_apply: "Apply this code at checkout (demo).",
    trade_generate: "Generate voucher code",
    diag_title: "Device diagnostics",
    diag_sub: "Tell us what’s wrong — we’ll suggest next steps.",
    diag_symptoms: "Symptoms",
    diag_water: "Liquid contact",
    diag_drop: "Dropped / impact",
    diag_battery: "Battery drains fast",
    diag_screen: "Screen issue",
    diag_sound: "No sound / mic",
    diag_submit: "Get suggestions",
    diag_result_title: "Suggestion",
    footer_services: "Services",
    nav_woo_store: "Live catalog",
    woo_store_title: "Shop",
    woo_store_sub: "Products from your WooCommerce store (REST API).",
    woo_loading: "Loading products…",
    woo_error: "Could not load products",
    woo_retry: "Try again",
    woo_empty: "No products found.",
    woo_syncing_more: "Loading more products from the store…",
    smartphones_breadcrumb: "Home / Smartphones",
    smartphones_hero_phones_title: "Smartphones",
    smartphones_hero_tablets_title: "Tablets",
    smartphones_hero_sub:
      "Shop by brand — quality stock for 700+ smartphone and tablet models.",
    smartphones_tab_phones: "Smartphones",
    smartphones_tab_tablets: "Tablets",
    smartphones_select_brand: "Select Your Brand",
    smartphones_select_tablet_brand: "Tablet brands",
    smartphones_parts_heading_default: "Featured products",
    smartphones_parts_heading_selected: "{brand}",
    smartphones_category_tablets_link: "Browse tablets",
    smartphones_search_brand: "Search smartphones & tablets…",
    smartphones_search_loading: "Searching catalog…",
    smartphones_search_results: "Results for “{query}”",
    smartphones_search_clear: "Clear search",
    smartphones_tablets_catalog_hint: "Connect WooCommerce to browse tablets in your live catalog.",
    woo_price_na: "Price not available",
    woo_env_title: "WooCommerce not configured",
    woo_env_body:
      "Set VITE_WOOCOMMERCE_STORE_URL, VITE_WOOCOMMERCE_CONSUMER_KEY, and VITE_WOOCOMMERCE_CONSUMER_SECRET in your environment (see .env.example). Restart the dev server after changing .env files.",
    model_accessories_title: "Accessories",
    model_accessories_hint: "Filter by part type for this model.",
    model_filter_all: "All",
    model_categories_title: "Store categories",
    model_acc_cases: "Cases & covers",
    model_acc_chargers: "Chargers & adapters",
    model_acc_screen_glass: "Screen protection",
    model_acc_camera_lens: "Camera & lens",
    model_acc_cables: "Cables",
    model_acc_audio: "Audio",
    model_acc_batteries: "Batteries & power",
    model_acc_screens_parts: "Screens & parts",
    model_acc_other: "Other",
  },
  pt: {
    welcome: "Bem-vindo à loja online da Samphone",
    phone: "+351-937119295",
    registration: "Registo",
    login: "Entrar",
    searchPlaceholder: "Pesquisar...",
    compare: "Comparar",
    wishlist: "Favoritos",
    allCategories: "Todas as Categorias",
    nav_home: "INÍCIO",
    nav_accessories: "ACESSÓRIOS",
    nav_smartphones: "SMARTPHONES",
    nav_cards: "CARTÕES",
    nav_new: "NOVIDADES",
    nav_multibrand: "MULTI MARCA",
    nav_contact: "CONTACTE-NOS",
    hero_badge: "Loja Nº 1 de Tech em Lisboa",
    hero_line1: "O Seu Telemóvel.",
    hero_line2: "As Suas Peças.",
    hero_line3: "Entregue Rápido.",
    hero_sub: "Acessórios premium e peças de reparação profissional para mais de 700+ modelos. Entrega rápida em Lisboa e Portugal.",
    hero_shop: "Comprar Agora",
    hero_browse: "Ver Categorias",
    hero_scroll: "Role para explorar marcas",
    hero_rating: "Classificação 4.9/5",
    hero_rating_sub: "de 600+ clientes satisfeitos",
    addToCart: "Adicionar ao Carrinho",
    viewParts: "Ver Peças",
    products_title: "Destaques da Semana",
    products_sub: "Milhares de produtos. Preços competitivos. Enviados rapidamente de Lisboa.",
    viewAll: "Ver Todos os Produtos",
    popularProducts: "Produtos Populares",
    productNotFound: "Não encontrámos este produto.",
    backToHome: "Voltar ao início",
    backToShopping: "Voltar à loja",
    reviewsLabel: "avaliações",
    newArrivals_section_title: "Novidades",
    newArrivals_section_sub: "Acabaram de chegar — veja as últimas adições!",
    newArrivals_see_all: "Ver tudo",
    newArrivals_page: "Página",
    newArrivals_of: "de",
    loginToSeePrice: "Inicie sessão para ver o preço",
    loginForPricing: "Inicie sessão para ver preços e adicionar produtos ao carrinho.",
    auth_register_title: "Criar conta",
    auth_login_title: "Bem-vindo de volta",
    auth_email: "E-mail",
    auth_password: "Palavra-passe",
    auth_name: "Nome completo",
    auth_submit_login: "Entrar",
    auth_submit_register: "Criar conta",
    auth_no_account: "Ainda não tem conta?",
    auth_has_account: "Já tem conta?",
    auth_logout: "Sair",
    auth_my_account: "A minha conta",
    account_title: "A minha conta",
    account_dashboard: "Painel",
    account_welcome: "Está autenticado. Explore a loja para ver preços e comprar.",
    account_profile_hint: "Complete o seu perfil para um checkout mais rápido.",
    breadcrumb_home: "Início",
    product_gallery_tab: "Galeria e zoom",
    product360_tab: "Vista 360°",
    product360_title: "Vista 360° do produto",
    product360_hint: "Arraste para a esquerda ou direita para rodar (demo com a imagem em 3D).",
    compare_page_title: "Comparar dispositivos",
    compare_page_sub: "Especificações lado a lado para peças e dispositivos.",
    compare_empty: "Adicione até 3 produtos nas respetivas páginas e volte a abrir comparar.",
    compare_add: "Adicionar à comparação",
    compare_remove: "Remover",
    compare_view: "Abrir comparação",
    compare_max_note: "Máximo 3 produtos. O mais antigo é substituído ao adicionar um quarto.",
    nav_cart: "Carrinho",
    cart_page_title: "O seu carrinho",
    cart_page_sub: "Revise artigos e quantidades. Preços visíveis com sessão iniciada.",
    cart_clear: "Esvaziar carrinho",
    cart_empty_title: "O carrinho está vazio",
    cart_empty_body: "Explore a loja e use o ícone do carrinho nos produtos para adicionar.",
    cart_remove_line: "Remover",
    cart_subtotal: "Subtotal",
    cart_subtotal_partial: "Alguns artigos sem preço listado; o subtotal pode estar incompleto.",
    cart_checkout_note: "Checkout é apenas demonstração — totais com preços visíveis do catálogo.",
    cart_checkout_cta: "Continuar para checkout",
    cart_items_count: "{count} artigos no carrinho",
    wishlist_page_title: "Favoritos",
    wishlist_page_sub: "Produtos guardados para mais tarde.",
    wishlist_empty_title: "A lista de favoritos está vazia",
    wishlist_empty_body: "Use o coração nos cartões de produto para guardar aqui.",
    wishlist_remove: "Guardado — toque para remover",
    wishlist_save: "Guardar nos favoritos",
    product_description_title: "Descrição do produto",
    product_details_title: "Detalhes do produto",
    product_compatibility: "Compatibilidade",
    product_in_stock: "Em stock",
    related_accessories_title: "Acessórios relacionados",
    related_accessories_see_all: "Ver tudo",
    woo_sku: "SKU",
    woo_categories_label: "Categorias",
    woo_product_type: "Tipo de produto",
    recently_viewed_title: "Vistos recentemente",
    compare_table_feature: "Funcionalidade",
    compare_clear_all: "Limpar tudo",
    stock_low: "Só {count} em stock",
    stock_in: "{count} em stock",
    delivery_title: "Estimativa de entrega",
    delivery_region: "Enviar para",
    delivery_zone_lisbon: "Área metropolitana Lisboa",
    delivery_zone_portugal: "Portugal continental",
    delivery_zone_islands: "Ilhas",
    delivery_speed_standard: "Standard",
    delivery_speed_express: "Expresso",
    delivery_speed_label: "Velocidade",
    delivery_arrives: "Chegada estimada",
    nav_track: "Acompanhar encomenda",
    nav_book_repair: "Marcar reparação",
    nav_trade_in: "Troca de equipamento",
    nav_diagnostics: "Diagnóstico",
    track_title: "Acompanhe a sua encomenda",
    track_sub: "Introduza o ID da encomenda (email de confirmação ou conta).",
    track_placeholder: "ex.: SP-LIS-…",
    track_button: "Acompanhar",
    track_not_found: "Encomenda não encontrada. Verifique o ID ou contacte pelo WhatsApp.",
    track_order_label: "Encomenda",
    track_step_ordered: "Encomenda registada",
    track_step_packed: "Embalado",
    track_step_shipped: "Enviado",
    track_step_delivery: "Em distribuição",
    track_step_done: "Entregue",
    track_items: "Artigos",
    support_open: "Ajuda e chat",
    support_tab_live: "Ao vivo",
    support_tab_faq: "Assistente FAQ",
    support_tab_callback: "Chamada",
    support_live_blurb: "Mais rápido: WhatsApp ou visite-nos em Lisboa. Respondemos seg–sáb no horário da loja.",
    support_chat_whatsapp: "Abrir WhatsApp",
    support_faq_placeholder: "Pergunte sobre envios, reparações, devoluções…",
    support_faq_send: "Perguntar",
    support_callback_hint: "Ligaremos de volta em breve, em horário comercial.",
    support_callback_phone: "Telemóvel",
    support_callback_ok: "Pedido enviado — ligamos em breve.",
    support_callback_submit: "Pedir chamada",
    people_also_bought_title: "Outros clientes compraram",
    recommended_title: "Recomendado para si",
    recommended_sub: "Com base na sua navegação",
    search_no_results: "Sem produtos correspondentes",
    search_suggestions: "Sugestões",
    account_orders: "As suas encomendas",
    account_track_link: "Acompanhar envio",
    account_create_order: "Criar encomenda a partir do carrinho",
    account_order_created: "Encomenda criada. Guarde este ID:",
    account_no_orders: "Ainda sem encomendas. Adicione produtos ao carrinho e crie uma encomenda aqui.",
    book_repair_title: "Marcar reparação",
    book_repair_sub: "Escolha serviços e urgência — o total atualiza em tempo real.",
    book_device_hint: "Dispositivo (marca / modelo)",
    book_notes: "Notas",
    book_services_label: "Serviços",
    book_urgency_standard: "Standard (3–5 dias)",
    book_urgency_same_day: "No próprio dia (+25 €)",
    book_total: "Total estimado",
    book_submit: "Enviar pedido de marcação",
    book_ok: "Pedido recebido — confirmamos por WhatsApp ou telefone.",
    trade_title: "Estimativa de troca",
    trade_sub: "Obtenha um voucher para a próxima compra.",
    trade_brand: "Marca",
    trade_age: "Idade do equipamento (anos)",
    trade_condition: "Estado",
    trade_estimate: "Valor estimado",
    trade_code_label: "Código do voucher",
    trade_copy: "Copiar código",
    trade_apply: "Utilize este código no checkout (demo).",
    trade_generate: "Gerar código de voucher",
    diag_title: "Diagnóstico do dispositivo",
    diag_sub: "Indique o problema — sugerimos os próximos passos.",
    diag_symptoms: "Sintomas",
    diag_water: "Contacto com líquidos",
    diag_drop: "Queda / impacto",
    diag_battery: "Bateria descarrega rápido",
    diag_screen: "Problema no ecrã",
    diag_sound: "Sem som / microfone",
    diag_submit: "Obter sugestões",
    diag_result_title: "Sugestão",
    footer_services: "Serviços",
    nav_woo_store: "Catálogo ao vivo",
    woo_store_title: "Loja",
    woo_store_sub: "Produtos da sua loja WooCommerce (API REST).",
    woo_loading: "A carregar produtos…",
    woo_error: "Não foi possível carregar os produtos",
    woo_retry: "Tentar novamente",
    woo_empty: "Nenhum produto encontrado.",
    woo_syncing_more: "A carregar mais produtos da loja…",
    smartphones_breadcrumb: "Início / Smartphones",
    smartphones_hero_phones_title: "Smartphones",
    smartphones_hero_tablets_title: "Tablets",
    smartphones_hero_sub:
      "Compre por marca — stock de qualidade para mais de 700 modelos de smartphone e tablet.",
    smartphones_tab_phones: "Smartphones",
    smartphones_tab_tablets: "Tablets",
    smartphones_select_brand: "Escolha a marca",
    smartphones_select_tablet_brand: "Marcas de tablet",
    smartphones_parts_heading_default: "Produtos em destaque",
    smartphones_parts_heading_selected: "{brand}",
    smartphones_category_tablets_link: "Ver tablets",
    smartphones_search_brand: "Pesquisar smartphones e tablets…",
    smartphones_search_loading: "A pesquisar no catálogo…",
    smartphones_search_results: "Resultados para “{query}”",
    smartphones_search_clear: "Limpar pesquisa",
    smartphones_tablets_catalog_hint:
      "Ligue o WooCommerce para ver tablets no catálogo em tempo real.",
    woo_price_na: "Preço indisponível",
    woo_env_title: "WooCommerce não configurado",
    woo_env_body:
      "Defina VITE_WOOCOMMERCE_STORE_URL, VITE_WOOCOMMERCE_CONSUMER_KEY e VITE_WOOCOMMERCE_CONSUMER_SECRET no ambiente (veja .env.example). Reinicie o servidor de desenvolvimento após alterar ficheiros .env.",
    model_accessories_title: "Acessórios",
    model_accessories_hint: "Filtre por tipo de peça para este modelo.",
    model_filter_all: "Todos",
    model_categories_title: "Categorias da loja",
    model_acc_cases: "Capas e fundas",
    model_acc_chargers: "Carregadores e adaptadores",
    model_acc_screen_glass: "Proteção de ecrã",
    model_acc_camera_lens: "Câmara e lentes",
    model_acc_cables: "Cabos",
    model_acc_audio: "Áudio",
    model_acc_batteries: "Baterias e energia",
    model_acc_screens_parts: "Ecrãs e peças",
    model_acc_other: "Outros",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey, vars?: Record<string, string | number>) => string;
}

const LangContext = createContext<LangContextValue>({
  lang: "en",
  setLang: () => {},
  t: (k) => k as string,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const stored = localStorage.getItem("samphone-lang");
    return stored === "pt" ? "pt" : "en";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("samphone-lang", l);
  };

  const t = useCallback((key: TranslationKey, vars?: Record<string, string | number>) => {
    let s = translations[lang][key] as string;
    if (vars) {
      for (const [k, v] of Object.entries(vars)) {
        s = s.replaceAll(`{${k}}`, String(v));
      }
    }
    return s;
  }, [lang]);

  const value = useMemo(() => ({ lang, setLang, t }), [lang, setLang, t]);

  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
