import { createContext, useCallback, useContext, useMemo, useState, type ReactNode } from "react";

export type Lang = "pt" | "en" | "fr" | "es" | "nl" | "hi" | "pa" | "ur";

export const LANG_OPTIONS: { id: Lang; label: string }[] = [
  { id: "pt", label: "Português" },
  { id: "en", label: "English" },
  { id: "fr", label: "Français" },
  { id: "es", label: "Español" },
  { id: "nl", label: "Nederlands" },
  { id: "hi", label: "हिन्दी" },
  { id: "pa", label: "ਪੰਜਾਬੀ" },
  { id: "ur", label: "اردو" },
];

const translations = {
  en: {
    welcome: "Welcome to Samphone's online store",
    phone: "+351-937119295",
    registration: "Registration",
    login: "Log In",
    searchPlaceholder: "To Search For...",
    lang_english: "English",
    lang_portuguese: "Português",
    compare: "Compare",
    wishlist: "Wishlist",
    allCategories: "All Categories",
    header_create_account: "Create an account",
    header_sign_in: "Sign In",
    header_menu: "Menu",
    nav_bar_others: "Others",
    nav_mega_see_all: "See All",
    nav_all_accessories: "All Accessories",
    nav_brands: "Brands",
    nav_browse_by: "Browse by",
    nav_view_all_brands: "View All Brands",
    nav_more_brands: "More Brands",
    nav_dark_mode: "Dark Mode",
    nav_secure_shopping: "Secure Shopping",
    nav_secure_shopping_sub: "100% secure & trusted checkout",
    search_products_brands: "Search for products, brands...",
    nav_bar_accessories: "Accessories",
    nav_bar_protection: "Protection",
    nav_bar_computing: "Computing",
    nav_bar_store: "Store",
    nav_bar_devices: "Devices",
    nav_bar_laptops: "Laptops",
    nav_home: "HOME",
    nav_accessories: "ACCESSORIES",
    nav_smartphones: "SMARTPHONES",
    nav_cards: "CARDS",
    nav_new: "NEW",
    nav_multibrand: "MULTI BRAND",
    nav_contact: "CONTACT US",
    hero_badge: "Lisbon's #1 Tech Boutique",
    hero_line1: "Your Phone.",
    hero_line2: "Your Parts.",
    hero_line3: "Delivered Fast.",
    hero_sub: "Premium accessories and pro-grade repair parts for over 700+ device models. Fast delivery across Lisbon and Portugal.",
    hero_shop: "Shop Now",
    hero_browse: "Browse Categories",
    hero_scroll: "Scroll to explore brands",
    hero_rating: "4.9/5 Rating",
    hero_rating_sub: "from 600+ happy customers",
    addToCart: "Add to Cart",
    viewParts: "View Parts",
    products_title: "Top Picks This Week",
    products_sub: "Thousands of products. Competitive prices. Shipped fast from Lisbon.",
    viewAll: "View All Products",
    popularProducts: "Popular Products",
    productNotFound: "We could not find this product.",
    backToHome: "Back to home",
    backToShopping: "Back to shopping",
    reviewsLabel: "reviews",
    newArrivals_section_title: "New Arrivals",
    newArrivals_section_sub: "Just landed — check out our latest additions!",
    newArrivals_see_all: "see all",
    newArrivals_page: "Page",
    newArrivals_of: "of",
    loginToSeePrice: "Log in to see price",
    login_for_price: "Login for price",
    featured_section_title: "Featured products",
    featured_section_sub: "Hand-picked parts and accessories for the workshop.",
    favorite_section_title: "Favorite products",
    favorite_section_sub: "Your favourites, always within reach!",
    crazy_deals_title: "Crazy Deals",
    badge_new: "New",
    badge_service: "Service Pack",
    cutoff_title: "Cut-Offs",
    cutoff_label: "CUT-OFF :",
    cutoff_time: "18h",
    cutoff_hint: "Orders placed before 18:00 ship the same day.",
    cutoff_shipping: "SHIPPING",
    cutoff_shipping_value: "Portugal",
    cutoff_shipping_hint: "Fast dispatch from Lisbon to all of Portugal.",
    cutoff_support: "SUPPORT",
    cutoff_support_hint: "WhatsApp and phone help during business hours.",
    home_services_title: "Services & support",
    home_service_repair: "Book a repair",
    home_service_repair_sub: "Screens, batteries and more — booked in minutes.",
    home_service_trade: "Trade-in",
    home_service_trade_sub: "Get value for your current phone towards a new one.",
    home_service_diag: "Device diagnostics",
    home_service_diag_sub: "Find the right part or repair for your model.",
    home_service_ship: "Track your order",
    home_service_ship_sub: "Same-day dispatch before 18:00 from Lisbon.",
    footer_need_help: "Need help?",
    footer_customer_service: "Customer service",
    footer_onboarding: "Onboarding",
    footer_account_mgmt: "Account Management",
    footer_orders_payments: "Order and Payment",
    footer_shipping: "Shipping and Delivery",
    footer_warranty: "Warranty and After-Sales Service",
    footer_email_support: "Email Support",
    footer_helpdesk: "Helpdesk",
    loginForPricing: "Sign in to view prices and add items to your cart.",
    auth_register_title: "Create account",
    auth_login_title: "Welcome back",
    auth_email: "Email",
    auth_password: "Password",
    auth_name: "Full name",
    auth_submit_login: "Sign in",
    auth_submit_register: "Create account",
    auth_no_account: "No account yet?",
    auth_has_account: "Already have an account?",
    auth_logout: "Log out",
    auth_my_account: "My account",
    account_title: "My Account",
    account_dashboard: "Dashboard",
    account_welcome: "You're signed in. Browse the store to see prices and shop.",
    account_profile_hint: "Complete your profile to speed up checkout.",
    breadcrumb_home: "Home",
    product_gallery_tab: "Gallery & zoom",
    product360_tab: "360° view",
    product360_title: "360° product view",
    product360_hint: "Drag left or right to rotate (demo uses your product image in 3D).",
    compare_page_title: "Compare devices",
    compare_page_sub: "Side-by-side specifications for parts and devices.",
    compare_empty: "Add up to 3 products from their pages, then open compare again.",
    compare_add: "Add to compare",
    compare_remove: "Remove",
    compare_view: "Open compare",
    compare_max_note: "Maximum 3 products. Oldest is replaced when adding a fourth.",
    nav_cart: "Cart",
    cart_page_title: "Your cart",
    cart_page_sub: "Review items and quantities. Prices shown when signed in.",
    cart_clear: "Clear cart",
    cart_empty_title: "Your cart is empty",
    cart_empty_body: "Browse the store and use the cart icon on product cards to add items.",
    cart_remove_line: "Remove",
    cart_subtotal: "Subtotal",
    cart_subtotal_partial: "Some items have no listed price; subtotal may be incomplete.",
    cart_checkout_note: "Pay securely with Stripe (card, MB WAY, Multibanco). Amounts are calculated on the server.",
    cart_checkout_cta: "Proceed to checkout",
    home_best_sellers: "Best Sellers",
    checkout_shipping: "Shipping",
    checkout_shipping_standard: "Home delivery",
    checkout_shipping_pickup: "Store pickup (Lisboa)",
    checkout_shipping_business: "Business delivery",
    checkout_full_name: "Full name",
    checkout_phone: "Phone",
    checkout_address: "Address",
    checkout_city: "City",
    checkout_postal: "Postal code",
    checkout_notes: "Order notes",
    checkout_pay: "Payment",
    checkout_pay_card: "Card (Visa / Mastercard / Amex)",
    checkout_pay_mbway: "MB WAY",
    checkout_pay_multibanco: "Multibanco",
    checkout_pay_cod: "Cash on delivery",
    checkout_pay_store: "Pay in store",
    checkout_success: "Thank you — your order was placed.",
    register_account_type: "Account type",
    register_personal: "Personal (B2C)",
    register_business: "Business / wholesale (B2B)",
    register_company: "Company name",
    register_vat: "VAT / NIF",
    register_business_type: "Business type",
    register_pending_wholesale: "Wholesale access is pending admin approval. You will see retail prices until then.",
    notify_stock: "Notify me when back in stock",
    notify_stock_ok: "We will email you when this item is available.",
    gdpr_export: "Download my data",
    gdpr_delete: "Delete my account",
    gdpr_delete_confirm: "Permanently delete your account and data?",
    order_cancel: "Cancel order",
    footer_privacy: "Privacy",
    footer_terms: "Terms",
    footer_refunds: "Refunds",
    footer_shipping_policy: "Shipping policy",
    footer_livro: "Livro de Reclamações",
    cart_items_count: "{count} items in cart",
    cart_sider_title: "My Cart",
    cart_sider_count_one: "{count} item in your cart",
    cart_sider_count_many: "{count} items in your cart",
    cart_sider_looking_good: "That's it! Your cart is looking good.",
    cart_sider_looking_good_sub: "Complete your order and enjoy fast & secure delivery.",
    cart_sider_clear: "Clear Shopping Cart",
    cart_sider_taxes: "Taxes and shipping calculated at checkout",
    cart_sider_review: "Review Cart",
    cart_sider_secure: "100% Secure Payment",
    cart_sider_delivery: "Fast Delivery",
    cart_sider_delivery_sub: "Across Europe",
    cart_sider_support: "Expert Support",
    cart_sider_support_sub: "Always here to help",
    cart_sider_continue: "Continue shopping",
    wishlist_page_title: "Wishlist",
    wishlist_page_sub: "Products you saved for later.",
    wishlist_empty_title: "Your wishlist is empty",
    wishlist_empty_body: "Use the heart on product cards to save items here.",
    wishlist_remove: "Saved — tap to remove",
    wishlist_save: "Save to wishlist",
    product_description_title: "Product description",
    product_details_title: "Product details",
    product_compatibility: "Compatibility",
    product_in_stock: "In stock",
    related_accessories_title: "Related accessories",
    related_accessories_see_all: "See all",
    woo_sku: "SKU",
    woo_categories_label: "Categories",
    woo_product_type: "Product type",
    recently_viewed_title: "Recently viewed",
    compare_table_feature: "Feature",
    compare_clear_all: "Clear all",
    stock_low: "Only {count} left in stock",
    stock_in: "{count} in stock",
    delivery_title: "Delivery estimate",
    delivery_region: "Ship to",
    delivery_zone_lisbon: "Lisbon metro",
    delivery_zone_portugal: "Portugal mainland",
    delivery_zone_islands: "Islands",
    delivery_speed_standard: "Standard",
    delivery_speed_express: "Express",
    delivery_speed_label: "Speed",
    delivery_arrives: "Estimated arrival",
    nav_track: "Track order",
    nav_book_repair: "Book repair",
    nav_trade_in: "Trade-in",
    nav_diagnostics: "Diagnostics",
    track_title: "Track your order",
    track_sub: "Enter your order ID from the confirmation email or your account.",
    track_placeholder: "e.g. SP-LIS-…",
    track_button: "Track",
    track_not_found: "We couldn’t find that order. Check the ID or contact us on WhatsApp.",
    track_login_hint: "Sign in to look up orders placed on your account.",
    track_order_label: "Order",
    track_step_ordered: "Order placed",
    track_step_packed: "Packed",
    track_step_shipped: "Shipped",
    track_step_delivery: "Out for delivery",
    track_step_done: "Delivered",
    track_items: "Items",
    support_open: "Help & chat",
    support_tab_live: "Live",
    support_tab_faq: "FAQ assistant",
    support_tab_callback: "Callback",
    support_live_blurb: "Fastest: WhatsApp or visit us in Lisbon. We reply Mon–Sat during store hours.",
    support_chat_whatsapp: "Open WhatsApp",
    support_faq_placeholder: "Ask about shipping, repairs, returns…",
    support_faq_send: "Ask",
    support_callback_hint: "We’ll call you back shortly during business hours.",
    support_callback_phone: "Phone number",
    support_callback_ok: "Request sent — we’ll call you soon.",
    support_callback_submit: "Request call",
    people_also_bought_title: "People also bought",
    recommended_title: "Favorite products",
    recommended_sub: "Based on what you browse",
    search_no_results: "No matching products",
    search_suggestions: "Suggestions",
    account_orders: "Your orders",
    account_track_link: "Track shipment",
    account_create_order: "Create order from cart",
    account_order_created: "Order created. Save this ID:",
    account_no_orders: "No orders yet. Add items to your cart and create an order here.",
    account_nav_my_account: "My account",
    account_nav_my_orders: "My orders",
    account_nav_my_returns: "My returns",
    account_nav_information: "My information",
    account_nav_2fa: "Two-factor authentication (2FA)",
    account_nav_vat: "Intra-Community VAT",
    account_nav_notifications: "Notifications",
    account_nav_payment: "My payment means",
    account_nav_orders: "My orders",
    account_nav_invoices: "My invoices",
    account_nav_payments_pending: "Payments pending",
    account_nav_ocadia: "Manage Ocadia",
    account_nav_restock: "Restock Alerts",
    account_nav_warranty: "Warranty Returns",
    account_nav_credit_notes: "My credit notes",
    account_nav_ewallet: "My e-wallet",
    account_profile_complete: "Your profile is {percent}% complete!",
    account_profile_complete_sub: "Complete your profile information to place your first order.",
    account_address_prompt: "Please enter your address to complete your profile.",
    account_save_address: "Save address",
    account_save_changes: "Save changes",
    account_field_street: "Street Address",
    account_field_street2: "Street Address 2",
    account_field_zip: "Zip/Postal Code",
    account_field_city: "City",
    account_field_country: "Country",
    account_field_phone: "Phone",
    account_field_company: "Company",
    account_use_delivery_address: "Use this address for delivery",
    account_turnover_title: "Turnover to date",
    account_analyse: "Analyse",
    account_chart_12m: "12 months",
    account_chart_90d: "90 days",
    account_chart_30d: "30 days",
    account_chart_7d: "7 days",
    account_statistics: "Statistics",
    account_statistics_period: "For the period",
    account_stat_turnover: "Turnover",
    account_stat_orders: "Number of orders",
    account_stat_qty: "Qty purchased",
    account_support_title: "Help us improve our customer support services",
    account_support_sub: "Contact the Samphone Team",
    account_2fa_desc: "Add an extra layer of security to your account with two-factor authentication.",
    account_2fa_enable: "Enable two-factor authentication",
    account_vat_desc: "Enter your intra-community VAT number for B2B invoicing.",
    account_vat_number: "VAT number",
    account_notif_orders: "Order updates and shipping",
    account_notif_promos: "Promotions and offers",
    account_notif_restock: "Restock alerts",
    account_payment_empty: "No payment methods saved yet.",
    account_payment_add: "Add payment method",
    account_invoices_empty: "No invoices yet. Invoices appear here after you place orders.",
    account_download_invoice: "Download PDF",
    account_payments_pending_empty: "You have no pending payments.",
    account_ocadia_desc: "Manage your Ocadia integration and wholesale settings with our team.",
    account_ocadia_contact: "Contact support",
    account_restock_empty: "No restock alerts yet.",
    account_restock_add: "Add alert",
    account_warranty_empty: "No warranty returns yet.",
    account_warranty_request: "Request warranty return",
    account_credit_empty: "No credit notes on your account.",
    account_credit_id: "Reference",
    account_credit_date: "Date",
    account_credit_amount: "Amount",
    account_ewallet_balance: "Available balance",
    account_ewallet_topup: "Request top-up",
    book_repair_title: "Book a repair",
    book_repair_sub: "Pick services and urgency — totals update live.",
    book_device_hint: "Device (brand / model)",
    book_notes: "Notes",
    book_services_label: "Services",
    book_urgency_standard: "Standard (3–5 days)",
    book_urgency_same_day: "Same-day (+€25)",
    book_total: "Estimated total",
    book_submit: "Submit booking request",
    book_whatsapp: "Send booking on WhatsApp",
    book_need_fields: "Add your name, phone, device, and at least one service.",
    book_ok: "WhatsApp is opening with your booking — the shop will confirm the slot.",
    trade_title: "Trade-in estimator",
    trade_sub: "Get a voucher toward your next purchase.",
    trade_brand: "Brand",
    trade_age: "Device age (years)",
    trade_condition: "Condition",
    trade_estimate: "Estimated value",
    trade_code_label: "Your voucher code",
    trade_copy: "Copy code",
    trade_apply: "This code is saved on your cart. The shop confirms the value when they receive the device.",
    trade_generate: "Generate voucher code",
    trade_whatsapp: "Confirm trade-in on WhatsApp",
    diag_title: "Device diagnostics",
    diag_sub: "Tell us what’s wrong — we’ll suggest next steps.",
    diag_symptoms: "Symptoms",
    diag_water: "Liquid contact",
    diag_drop: "Dropped / impact",
    diag_battery: "Battery drains fast",
    diag_screen: "Screen issue",
    diag_sound: "No sound / mic",
    diag_submit: "Get suggestions",
    diag_result_title: "Suggestion",
    diag_book: "Book this repair",
    diag_parts: "Matching parts in the shop",
    footer_services: "Services",
    nav_woo_store: "Live catalog",
    woo_store_title: "Shop",
    woo_store_sub: "Products from your WooCommerce store (REST API).",
    woo_loading: "Loading products…",
    woo_error: "Could not load products",
    woo_retry: "Try again",
    woo_empty: "No products found.",
    woo_syncing_more: "Loading more products from the store…",
    smartphones_breadcrumb: "Home / Smartphones",
    smartphones_hero_phones_title: "Smartphones",
    smartphones_hero_tablets_title: "Tablets",
    smartphones_hero_sub:
      "Shop by brand — quality stock for 700+ smartphone and tablet models.",
    smartphones_tab_phones: "Smartphones",
    smartphones_tab_tablets: "Tablets",
    smartphones_select_brand: "Select Your Brand",
    smartphones_select_tablet_brand: "Tablet brands",
    smartphones_parts_heading_default: "Featured products",
    smartphones_parts_heading_selected: "{brand}",
    smartphones_category_tablets_link: "Browse tablets",
    smartphones_search_brand: "Search smartphones & tablets…",
    smartphones_search_loading: "Searching catalog…",
    smartphones_search_results: "Results for “{query}”",
    smartphones_search_clear: "Clear search",
    smartphones_tablets_catalog_hint: "Connect WooCommerce to browse tablets in your live catalog.",
    woo_price_na: "Price not available",
    woo_env_title: "WooCommerce not configured",
    woo_env_body:
      "Start the API server with WOOCOMMERCE_* credentials (see docs/SECURITY.md). The storefront loads the catalog via /api/woocommerce — keys must not be in VITE_ env vars.",
    model_accessories_title: "Accessories",
    model_accessories_hint: "Filter by part type for this model.",
    model_filter_all: "All",
    model_categories_title: "Store categories",
    model_acc_cases: "Cases & covers",
    model_acc_chargers: "Chargers & adapters",
    model_acc_screen_glass: "Screen protection",
    model_acc_camera_lens: "Camera & lens",
    model_acc_cables: "Cables",
    model_acc_audio: "Audio",
    model_acc_batteries: "Batteries & power",
    model_acc_screens_parts: "Screens & parts",
    model_acc_other: "Other",
  },
  pt: {
    welcome: "Bem-vindo à loja online da Samphone",
    phone: "+351-937119295",
    registration: "Registo",
    login: "Entrar",
    searchPlaceholder: "Procurar por...",
    lang_english: "English",
    lang_portuguese: "Português",
    compare: "Comparar",
    wishlist: "Favoritos",
    allCategories: "Todas as Categorias",
    header_create_account: "Criar conta",
    header_sign_in: "Entrar",
    header_menu: "Menu",
    nav_bar_others: "Outros",
    nav_mega_see_all: "Ver tudo",
    nav_all_accessories: "Todos os acessórios",
    nav_brands: "Marcas",
    nav_browse_by: "Explorar por",
    nav_view_all_brands: "Ver todas as marcas",
    nav_more_brands: "Mais marcas",
    nav_dark_mode: "Modo escuro",
    nav_secure_shopping: "Compras seguras",
    nav_secure_shopping_sub: "Checkout 100% seguro e fiável",
    search_products_brands: "Procurar produtos, marcas...",
    nav_bar_accessories: "Acessórios",
    nav_bar_protection: "Proteção",
    nav_bar_computing: "Informática",
    nav_bar_store: "Loja",
    nav_bar_devices: "Dispositivos",
    nav_bar_laptops: "Portáteis",
    nav_home: "INÍCIO",
    nav_accessories: "ACESSÓRIOS",
    nav_smartphones: "SMARTPHONES",
    nav_cards: "CARTÕES",
    nav_new: "NOVIDADES",
    nav_multibrand: "MULTI MARCA",
    nav_contact: "CONTACTE-NOS",
    hero_badge: "Loja Nº 1 de Tech em Lisboa",
    hero_line1: "O Seu Telemóvel.",
    hero_line2: "As Suas Peças.",
    hero_line3: "Entregue Rápido.",
    hero_sub: "Acessórios premium e peças de reparação profissional para mais de 700+ modelos. Entrega rápida em Lisboa e Portugal.",
    hero_shop: "Comprar Agora",
    hero_browse: "Ver Categorias",
    hero_scroll: "Role para explorar marcas",
    hero_rating: "Classificação 4.9/5",
    hero_rating_sub: "de 600+ clientes satisfeitos",
    addToCart: "Adicionar ao Carrinho",
    viewParts: "Ver Peças",
    products_title: "Destaques da Semana",
    products_sub: "Milhares de produtos. Preços competitivos. Enviados rapidamente de Lisboa.",
    viewAll: "Ver Todos os Produtos",
    popularProducts: "Produtos Populares",
    productNotFound: "Não encontrámos este produto.",
    backToHome: "Voltar ao início",
    backToShopping: "Voltar à loja",
    reviewsLabel: "avaliações",
    newArrivals_section_title: "Novidades",
    newArrivals_section_sub: "Acabaram de chegar — veja as últimas adições!",
    newArrivals_see_all: "ver tudo",
    newArrivals_page: "Página",
    newArrivals_of: "de",
    loginToSeePrice: "Inicie sessão para ver o preço",
    login_for_price: "Login para ver preço",
    featured_section_title: "Produtos em destaque",
    featured_section_sub: "Peças e acessórios escolhidos para a oficina.",
    favorite_section_title: "Produtos favoritos",
    favorite_section_sub: "Os seus favoritos, sempre à mão!",
    crazy_deals_title: "Crazy Deals",
    badge_new: "Novo",
    badge_service: "Service Pack",
    cutoff_title: "Cut-Offs",
    cutoff_label: "CUT-OFF :",
    cutoff_time: "18h",
    cutoff_hint: "Encomendas até às 18:00 saem no mesmo dia.",
    cutoff_shipping: "ENVIO",
    cutoff_shipping_value: "Portugal",
    cutoff_shipping_hint: "Expedição rápida a partir de Lisboa para todo o país.",
    cutoff_support: "APOIO",
    cutoff_support_hint: "Ajuda por WhatsApp e telefone em horário comercial.",
    home_services_title: "Serviços e apoio",
    home_service_repair: "Marcar reparação",
    home_service_repair_sub: "Ecrãs, baterias e mais — marcação em minutos.",
    home_service_trade: "Retoma",
    home_service_trade_sub: "Valorize o telemóvel atual na compra de um novo.",
    home_service_diag: "Diagnóstico",
    home_service_diag_sub: "Encontre a peça ou reparação certa para o seu modelo.",
    home_service_ship: "Siga a encomenda",
    home_service_ship_sub: "Expedição no mesmo dia até às 18:00 a partir de Lisboa.",
    footer_need_help: "Precisa de ajuda?",
    footer_customer_service: "Serviço de cliente",
    footer_onboarding: "Onboarding",
    footer_account_mgmt: "Gestão de conta",
    footer_orders_payments: "Encomenda e pagamento",
    footer_shipping: "Envio e entrega",
    footer_warranty: "Garantia e pós-venda",
    footer_email_support: "Apoio por email",
    footer_helpdesk: "Helpdesk",
    loginForPricing: "Inicie sessão para ver preços e adicionar produtos ao carrinho.",
    auth_register_title: "Criar conta",
    auth_login_title: "Bem-vindo de volta",
    auth_email: "E-mail",
    auth_password: "Palavra-passe",
    auth_name: "Nome completo",
    auth_submit_login: "Entrar",
    auth_submit_register: "Criar conta",
    auth_no_account: "Ainda não tem conta?",
    auth_has_account: "Já tem conta?",
    auth_logout: "Sair",
    auth_my_account: "A minha conta",
    account_title: "A minha conta",
    account_dashboard: "Painel",
    account_welcome: "Está autenticado. Explore a loja para ver preços e comprar.",
    account_profile_hint: "Complete o seu perfil para um checkout mais rápido.",
    breadcrumb_home: "Início",
    product_gallery_tab: "Galeria e zoom",
    product360_tab: "Vista 360°",
    product360_title: "Vista 360° do produto",
    product360_hint: "Arraste para a esquerda ou direita para rodar (demo com a imagem em 3D).",
    compare_page_title: "Comparar dispositivos",
    compare_page_sub: "Especificações lado a lado para peças e dispositivos.",
    compare_empty: "Adicione até 3 produtos nas respetivas páginas e volte a abrir comparar.",
    compare_add: "Adicionar à comparação",
    compare_remove: "Remover",
    compare_view: "Abrir comparação",
    compare_max_note: "Máximo 3 produtos. O mais antigo é substituído ao adicionar um quarto.",
    nav_cart: "Carrinho",
    cart_page_title: "O seu carrinho",
    cart_page_sub: "Revise artigos e quantidades. Preços visíveis com sessão iniciada.",
    cart_clear: "Esvaziar carrinho",
    cart_empty_title: "O carrinho está vazio",
    cart_empty_body: "Explore a loja e use o ícone do carrinho nos produtos para adicionar.",
    cart_remove_line: "Remover",
    cart_subtotal: "Subtotal",
    cart_subtotal_partial: "Alguns artigos sem preço listado; o subtotal pode estar incompleto.",
    cart_checkout_note: "Pagamento seguro via Stripe (cartão, MB WAY, Multibanco). Os valores são calculados no servidor.",
    cart_checkout_cta: "Continuar para checkout",
    home_best_sellers: "Mais vendidos",
    checkout_shipping: "Envio",
    checkout_shipping_standard: "Entrega ao domicílio",
    checkout_shipping_pickup: "Levantamento em loja (Lisboa)",
    checkout_shipping_business: "Entrega empresarial",
    checkout_full_name: "Nome completo",
    checkout_phone: "Telefone",
    checkout_address: "Morada",
    checkout_city: "Cidade",
    checkout_postal: "Código postal",
    checkout_notes: "Notas da encomenda",
    checkout_pay: "Pagamento",
    checkout_pay_card: "Cartão (Visa / Mastercard / Amex)",
    checkout_pay_mbway: "MB WAY",
    checkout_pay_multibanco: "Multibanco",
    checkout_pay_cod: "Pagamento na entrega",
    checkout_pay_store: "Pagar na loja",
    checkout_success: "Obrigado — a sua encomenda foi registada.",
    register_account_type: "Tipo de conta",
    register_personal: "Particular (B2C)",
    register_business: "Empresa / retalho (B2B)",
    register_company: "Nome da empresa",
    register_vat: "NIF / IVA",
    register_business_type: "Tipo de negócio",
    register_pending_wholesale: "O acesso grossista aguarda aprovação. Até lá vê preços de retalho.",
    notify_stock: "Avisar-me quando voltar",
    notify_stock_ok: "Enviamos um email quando estiver disponível.",
    gdpr_export: "Descarregar os meus dados",
    gdpr_delete: "Eliminar a minha conta",
    gdpr_delete_confirm: "Eliminar permanentemente a conta e os dados?",
    order_cancel: "Cancelar encomenda",
    footer_privacy: "Privacidade",
    footer_terms: "Termos",
    footer_refunds: "Devoluções",
    footer_shipping_policy: "Política de envio",
    footer_livro: "Livro de Reclamações",
    cart_items_count: "{count} artigos no carrinho",
    cart_sider_title: "O meu carrinho",
    cart_sider_count_one: "{count} artigo no carrinho",
    cart_sider_count_many: "{count} artigos no carrinho",
    cart_sider_looking_good: "É isto! O carrinho está pronto.",
    cart_sider_looking_good_sub: "Conclua a encomenda e aproveite uma entrega rápida e segura.",
    cart_sider_clear: "Esvaziar carrinho",
    cart_sider_taxes: "Impostos e portes calculados no checkout",
    cart_sider_review: "Ver carrinho",
    cart_sider_secure: "Pagamento 100% seguro",
    cart_sider_delivery: "Entrega rápida",
    cart_sider_delivery_sub: "Em toda a Europa",
    cart_sider_support: "Apoio especializado",
    cart_sider_support_sub: "Sempre por perto",
    cart_sider_continue: "Continuar a comprar",
    wishlist_page_title: "Favoritos",
    wishlist_page_sub: "Produtos guardados para mais tarde.",
    wishlist_empty_title: "A lista de favoritos está vazia",
    wishlist_empty_body: "Use o coração nos cartões de produto para guardar aqui.",
    wishlist_remove: "Guardado — toque para remover",
    wishlist_save: "Guardar nos favoritos",
    product_description_title: "Descrição do produto",
    product_details_title: "Detalhes do produto",
    product_compatibility: "Compatibilidade",
    product_in_stock: "Em stock",
    related_accessories_title: "Acessórios relacionados",
    related_accessories_see_all: "Ver tudo",
    woo_sku: "SKU",
    woo_categories_label: "Categorias",
    woo_product_type: "Tipo de produto",
    recently_viewed_title: "Vistos recentemente",
    compare_table_feature: "Funcionalidade",
    compare_clear_all: "Limpar tudo",
    stock_low: "Só {count} em stock",
    stock_in: "{count} em stock",
    delivery_title: "Estimativa de entrega",
    delivery_region: "Enviar para",
    delivery_zone_lisbon: "Área metropolitana Lisboa",
    delivery_zone_portugal: "Portugal continental",
    delivery_zone_islands: "Ilhas",
    delivery_speed_standard: "Standard",
    delivery_speed_express: "Expresso",
    delivery_speed_label: "Velocidade",
    delivery_arrives: "Chegada estimada",
    nav_track: "Acompanhar encomenda",
    nav_book_repair: "Marcar reparação",
    nav_trade_in: "Troca de equipamento",
    nav_diagnostics: "Diagnóstico",
    track_title: "Acompanhe a sua encomenda",
    track_sub: "Introduza o ID da encomenda (email de confirmação ou conta).",
    track_placeholder: "ex.: SP-LIS-…",
    track_button: "Acompanhar",
    track_not_found: "Encomenda não encontrada. Verifique o ID ou contacte pelo WhatsApp.",
    track_login_hint: "Inicie sessão para consultar as encomendas da sua conta.",
    track_order_label: "Encomenda",
    track_step_ordered: "Encomenda registada",
    track_step_packed: "Embalado",
    track_step_shipped: "Enviado",
    track_step_delivery: "Em distribuição",
    track_step_done: "Entregue",
    track_items: "Artigos",
    support_open: "Ajuda e chat",
    support_tab_live: "Ao vivo",
    support_tab_faq: "Assistente FAQ",
    support_tab_callback: "Chamada",
    support_live_blurb: "Mais rápido: WhatsApp ou visite-nos em Lisboa. Respondemos seg–sáb no horário da loja.",
    support_chat_whatsapp: "Abrir WhatsApp",
    support_faq_placeholder: "Pergunte sobre envios, reparações, devoluções…",
    support_faq_send: "Perguntar",
    support_callback_hint: "Ligaremos de volta em breve, em horário comercial.",
    support_callback_phone: "Telemóvel",
    support_callback_ok: "Pedido enviado — ligamos em breve.",
    support_callback_submit: "Pedir chamada",
    people_also_bought_title: "Outros clientes compraram",
    recommended_title: "Produtos favoritos",
    recommended_sub: "Com base na sua navegação",
    search_no_results: "Sem produtos correspondentes",
    search_suggestions: "Sugestões",
    account_orders: "As suas encomendas",
    account_track_link: "Acompanhar envio",
    account_create_order: "Criar encomenda a partir do carrinho",
    account_order_created: "Encomenda criada. Guarde este ID:",
    account_no_orders: "Ainda sem encomendas. Adicione produtos ao carrinho e crie uma encomenda aqui.",
    account_nav_my_account: "A minha conta",
    account_nav_my_orders: "As minhas encomendas",
    account_nav_my_returns: "As minhas devoluções",
    account_nav_information: "Os meus dados",
    account_nav_2fa: "Autenticação de dois fatores (2FA)",
    account_nav_vat: "IVA intracomunitário",
    account_nav_notifications: "Notificações",
    account_nav_payment: "Os meus meios de pagamento",
    account_nav_orders: "As minhas encomendas",
    account_nav_invoices: "As minhas faturas",
    account_nav_payments_pending: "Pagamentos pendentes",
    account_nav_ocadia: "Gerir Ocadia",
    account_nav_restock: "Alertas de reabastecimento",
    account_nav_warranty: "Devoluções em garantia",
    account_nav_credit_notes: "As minhas notas de crédito",
    account_nav_ewallet: "A minha e-wallet",
    account_profile_complete: "O seu perfil está {percent}% completo!",
    account_profile_complete_sub: "Complete os dados do perfil para fazer a primeira encomenda.",
    account_address_prompt: "Introduza a sua morada para completar o perfil.",
    account_save_address: "Guardar morada",
    account_save_changes: "Guardar alterações",
    account_field_street: "Morada",
    account_field_street2: "Morada (linha 2)",
    account_field_zip: "Código postal",
    account_field_city: "Cidade",
    account_field_country: "País",
    account_field_phone: "Telefone",
    account_field_company: "Empresa",
    account_use_delivery_address: "Usar esta morada para entrega",
    account_turnover_title: "Volume de negócios até à data",
    account_analyse: "Analisar",
    account_chart_12m: "12 meses",
    account_chart_90d: "90 dias",
    account_chart_30d: "30 dias",
    account_chart_7d: "7 dias",
    account_statistics: "Estatísticas",
    account_statistics_period: "No período",
    account_stat_turnover: "Volume de negócios",
    account_stat_orders: "N.º de encomendas",
    account_stat_qty: "Qtd. comprada",
    account_support_title: "Ajude-nos a melhorar o apoio ao cliente",
    account_support_sub: "Contacte a equipa Samphone",
    account_2fa_desc: "Adicione uma camada extra de segurança à sua conta com 2FA.",
    account_2fa_enable: "Ativar autenticação de dois fatores",
    account_vat_desc: "Introduza o seu número de IVA intracomunitário para faturação B2B.",
    account_vat_number: "Número de IVA",
    account_notif_orders: "Atualizações de encomendas e envio",
    account_notif_promos: "Promoções e ofertas",
    account_notif_restock: "Alertas de stock",
    account_payment_empty: "Ainda sem meios de pagamento guardados.",
    account_payment_add: "Adicionar meio de pagamento",
    account_invoices_empty: "Ainda sem faturas. Aparecem aqui após encomendar.",
    account_download_invoice: "Descarregar PDF",
    account_payments_pending_empty: "Não tem pagamentos pendentes.",
    account_ocadia_desc: "Gerir a integração Ocadia e definições grossista com a nossa equipa.",
    account_ocadia_contact: "Contactar apoio",
    account_restock_empty: "Ainda sem alertas de reabastecimento.",
    account_restock_add: "Adicionar alerta",
    account_warranty_empty: "Ainda sem devoluções em garantia.",
    account_warranty_request: "Pedir devolução em garantia",
    account_credit_empty: "Sem notas de crédito na conta.",
    account_credit_id: "Referência",
    account_credit_date: "Data",
    account_credit_amount: "Montante",
    account_ewallet_balance: "Saldo disponível",
    account_ewallet_topup: "Pedir carregamento",
    book_repair_title: "Marcar reparação",
    book_repair_sub: "Escolha serviços e urgência — o total atualiza em tempo real.",
    book_device_hint: "Dispositivo (marca / modelo)",
    book_notes: "Notas",
    book_services_label: "Serviços",
    book_urgency_standard: "Standard (3–5 dias)",
    book_urgency_same_day: "No próprio dia (+25 €)",
    book_total: "Total estimado",
    book_submit: "Enviar pedido de marcação",
    book_whatsapp: "Enviar marcação no WhatsApp",
    book_need_fields: "Indique nome, telefone, dispositivo e pelo menos um serviço.",
    book_ok: "O WhatsApp vai abrir com o pedido — a loja confirma o horário.",
    trade_title: "Estimativa de troca",
    trade_sub: "Obtenha um voucher para a próxima compra.",
    trade_brand: "Marca",
    trade_age: "Idade do equipamento (anos)",
    trade_condition: "Estado",
    trade_estimate: "Valor estimado",
    trade_code_label: "Código do voucher",
    trade_copy: "Copiar código",
    trade_apply: "O código fica guardado no carrinho. A loja confirma o valor quando receber o equipamento.",
    trade_generate: "Gerar código de voucher",
    trade_whatsapp: "Confirmar troca no WhatsApp",
    diag_title: "Diagnóstico do dispositivo",
    diag_sub: "Indique o problema — sugerimos os próximos passos.",
    diag_symptoms: "Sintomas",
    diag_water: "Contacto com líquidos",
    diag_drop: "Queda / impacto",
    diag_battery: "Bateria descarrega rápido",
    diag_screen: "Problema no ecrã",
    diag_sound: "Sem som / microfone",
    diag_submit: "Obter sugestões",
    diag_result_title: "Sugestão",
    diag_book: "Marcar esta reparação",
    diag_parts: "Peças correspondentes na loja",
    footer_services: "Serviços",
    nav_woo_store: "Catálogo ao vivo",
    woo_store_title: "Loja",
    woo_store_sub: "Produtos da sua loja WooCommerce (API REST).",
    woo_loading: "A carregar produtos…",
    woo_error: "Não foi possível carregar os produtos",
    woo_retry: "Tentar novamente",
    woo_empty: "Nenhum produto encontrado.",
    woo_syncing_more: "A carregar mais produtos da loja…",
    smartphones_breadcrumb: "Início / Smartphones",
    smartphones_hero_phones_title: "Smartphones",
    smartphones_hero_tablets_title: "Tablets",
    smartphones_hero_sub:
      "Compre por marca — stock de qualidade para mais de 700 modelos de smartphone e tablet.",
    smartphones_tab_phones: "Smartphones",
    smartphones_tab_tablets: "Tablets",
    smartphones_select_brand: "Escolha a marca",
    smartphones_select_tablet_brand: "Marcas de tablet",
    smartphones_parts_heading_default: "Produtos em destaque",
    smartphones_parts_heading_selected: "{brand}",
    smartphones_category_tablets_link: "Ver tablets",
    smartphones_search_brand: "Pesquisar smartphones e tablets…",
    smartphones_search_loading: "A pesquisar no catálogo…",
    smartphones_search_results: "Resultados para “{query}”",
    smartphones_search_clear: "Limpar pesquisa",
    smartphones_tablets_catalog_hint:
      "Ligue o WooCommerce para ver tablets no catálogo em tempo real.",
    woo_price_na: "Preço indisponível",
    woo_env_title: "WooCommerce não configurado",
    woo_env_body:
      "Inicie o servidor API com credenciais WOOCOMMERCE_* (veja docs/SECURITY.md). O catálogo usa /api/woocommerce — as chaves não devem estar em variáveis VITE_.",
    model_accessories_title: "Acessórios",
    model_accessories_hint: "Filtre por tipo de peça para este modelo.",
    model_filter_all: "Todos",
    model_categories_title: "Categorias da loja",
    model_acc_cases: "Capas e fundas",
    model_acc_chargers: "Carregadores e adaptadores",
    model_acc_screen_glass: "Proteção de ecrã",
    model_acc_camera_lens: "Câmara e lentes",
    model_acc_cables: "Cabos",
    model_acc_audio: "Áudio",
    model_acc_batteries: "Baterias e energia",
    model_acc_screens_parts: "Ecrãs e peças",
    model_acc_other: "Outros",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

interface LangContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey, vars?: Record<string, string | number>) => string;
}

const LangContext = createContext<LangContextValue>({
  lang: "en",
  setLang: () => {},
  t: (k) => k as string,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const stored = localStorage.getItem("samphone-lang");
    return LANG_OPTIONS.some((o) => o.id === stored) ? (stored as Lang) : "pt";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("samphone-lang", l);
  };

  const t = useCallback((key: TranslationKey, vars?: Record<string, string | number>) => {
    const table = lang === "pt" ? translations.pt : translations.en;
    let s = (table[key] ?? translations.en[key]) as string;
    if (vars) {
      for (const [k, v] of Object.entries(vars)) {
        s = s.replaceAll(`{${k}}`, String(v));
      }
    }
    return s;
  }, [lang]);

  const value = useMemo(() => ({ lang, setLang, t }), [lang, setLang, t]);

  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
